---
name: jc
title: Convert command output to json
summary: CLI tool that converts the output command-line tools to JSON
description: |
    CLI tool and python library that converts the output of popular command-line
    tools, file-types, and common strings to JSON, YAML, or Dictionaries.
    This allows piping of output to tools like jq and simplifying automation scripts.
# version: git
base: core22
confinement: strict
license: MIT
type: app

website: https://github.com/kellyjonbrazil/jc
contact: Kelly Brazil <kellyjonbrazil@gmail.com>
source-code: https://github.com/kellyjonbrazil/jc
issues: https://github.com/kellyjonbrazil/jc/issues

adopt-info: jc

parts:
  jc:
    plugin: python
    source: .
    # pulled v1.17.2, `git describe`
    # source: https://github.com/kellyjonbrazil/jc
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(grep version= setup.py | cut -d '=' -f 2 | sed "s/,$// ; s/'//g")
      snapcraftctl set-grade "stable"

apps:
  jc:
    command: bin/jc
    environment:
      LC_ALL: C.UTF-8
